/**
 * VolumnBook — Comprehensive Export Facilities
 * Generates official PDF, DOCX (Microsoft Word), and XLS/XLSX (Microsoft Excel) reports.
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import {
  Document,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
  AlignmentType,
  BorderStyle,
  Header,
  Footer,
  PageNumber,
} from 'docx';
import { VolumeRecord } from '../types';
import { formatToDisplayDate, formatFullDateTime, getTodayDbDate } from './dateUtils';
import { logger } from './logger';

export interface ExportReportOptions {
  title?: string;
  subtitle?: string;
  filterDescription?: string;
  orientation?: 'portrait' | 'landscape';
}

/**
 * Downloads a Blob as a file in the browser or via Electron
 */
export function triggerFileDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Export records as A4 PDF document
 */
export async function exportToPdf(records: VolumeRecord[], options: ExportReportOptions = {}): Promise<void> {
  try {
    const title = options.title || 'Case & Judgement Volume Records';
    const orientation = options.orientation || 'landscape';
    const doc = new jsPDF({
      orientation: orientation,
      unit: 'mm',
      format: 'a4',
    });

    const pageCountPlaceholder = '{total_pages_count_string}';
    const generatedAt = formatFullDateTime(new Date());
    const filterInfo = options.filterDescription ? `Filter: ${options.filterDescription}` : 'All Records';

    // Header styling
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(30, 58, 138); // Deep Navy #1e3a8a
    doc.text('VOLUMNBOOK', 14, 15);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105); // Slate 600
    doc.text('Case & Judgement Volume Management System', 14, 21);

    // Title and Meta
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42); // Slate 900
    doc.text(`Report: ${title}`, 14, 29);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated: ${generatedAt}  |  ${filterInfo}  |  Total Records: ${records.length}`, 14, 34);

    // Build Table Rows
    const tableData = records.map((r) => [
      String(r.SerialNo),
      r.CaseNo || '—',
      formatToDisplayDate(r.JudgementDate) || '—',
      formatToDisplayDate(r.DraftDate) || '—',
      formatToDisplayDate(r.FinalDate) || '—',
      formatToDisplayDate(r.SendToSectionDate) || '—',
      r.Remarks || '',
    ]);

    autoTable(doc, {
      startY: 38,
      head: [['Sl', 'Case No', 'Judgement Date', 'Draft Date', 'Final Date', 'Send to Section', 'Remarks']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: [30, 58, 138],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 8.5,
        halign: 'left',
      },
      styles: {
        fontSize: 8,
        cellPadding: 2,
        textColor: [30, 41, 59],
        lineColor: [226, 232, 240],
        lineWidth: 0.1,
      },
      columnStyles: {
        0: { cellWidth: 12, halign: 'center' },
        1: { cellWidth: 32, fontStyle: 'bold' },
        2: { cellWidth: 26, halign: 'center' },
        3: { cellWidth: 26, halign: 'center' },
        4: { cellWidth: 26, halign: 'center' },
        5: { cellWidth: 28, halign: 'center' },
        6: { cellWidth: 'auto' },
      },
      didDrawPage: (data) => {
        // Footer on each page
        const pageSize = doc.internal.pageSize;
        const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
        const pageWidth = pageSize.width ? pageSize.width : pageSize.getWidth();

        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text('Generated by VolumnBook — Confidential Office Record', 14, pageHeight - 8);

        const pageStr = `Page ${data.pageNumber} of ${pageCountPlaceholder}`;
        doc.text(pageStr, pageWidth - 35, pageHeight - 8);
      },
    });

    // Replace total page count
    if (typeof (doc as any).putTotalPages === 'function') {
      (doc as any).putTotalPages(pageCountPlaceholder);
    }

    const filename = `VolumnBook_Report_${getTodayDbDate()}.pdf`;
    doc.save(filename);
    logger.info('EXPORT', `PDF exported successfully: ${filename} (${records.length} records)`);
  } catch (err: any) {
    logger.error('EXPORT', `Failed to export PDF: ${err?.message}`);
    throw err;
  }
}

/**
 * Export records as formatted Microsoft Word document (.docx)
 */
export async function exportToDocx(records: VolumeRecord[], options: ExportReportOptions = {}): Promise<void> {
  try {
    const title = options.title || 'Case & Judgement Volume Records';
    const generatedAt = formatFullDateTime(new Date());
    const filterInfo = options.filterDescription ? `Filter: ${options.filterDescription}` : 'All Records';

    const tableRows = [
      new TableRow({
        tableHeader: true,
        children: [
          new TableCell({
            width: { size: 8, type: WidthType.PERCENTAGE },
            shading: { fill: '1E3A8A' },
            children: [new Paragraph({ children: [new TextRun({ text: 'Sl', bold: true, color: 'FFFFFF' })] })],
          }),
          new TableCell({
            width: { size: 20, type: WidthType.PERCENTAGE },
            shading: { fill: '1E3A8A' },
            children: [new Paragraph({ children: [new TextRun({ text: 'Case No', bold: true, color: 'FFFFFF' })] })],
          }),
          new TableCell({
            width: { size: 14, type: WidthType.PERCENTAGE },
            shading: { fill: '1E3A8A' },
            children: [new Paragraph({ children: [new TextRun({ text: 'Judgement Date', bold: true, color: 'FFFFFF' })] })],
          }),
          new TableCell({
            width: { size: 14, type: WidthType.PERCENTAGE },
            shading: { fill: '1E3A8A' },
            children: [new Paragraph({ children: [new TextRun({ text: 'Draft Date', bold: true, color: 'FFFFFF' })] })],
          }),
          new TableCell({
            width: { size: 14, type: WidthType.PERCENTAGE },
            shading: { fill: '1E3A8A' },
            children: [new Paragraph({ children: [new TextRun({ text: 'Final Date', bold: true, color: 'FFFFFF' })] })],
          }),
          new TableCell({
            width: { size: 15, type: WidthType.PERCENTAGE },
            shading: { fill: '1E3A8A' },
            children: [new Paragraph({ children: [new TextRun({ text: 'Send to Section', bold: true, color: 'FFFFFF' })] })],
          }),
          new TableCell({
            width: { size: 15, type: WidthType.PERCENTAGE },
            shading: { fill: '1E3A8A' },
            children: [new Paragraph({ children: [new TextRun({ text: 'Remarks', bold: true, color: 'FFFFFF' })] })],
          }),
        ],
      }),
      ...records.map((r, index) => {
        const bg = index % 2 === 0 ? 'FFFFFF' : 'F8FAFC';
        return new TableRow({
          children: [
            new TableCell({
              shading: { fill: bg },
              children: [new Paragraph(String(r.SerialNo))],
            }),
            new TableCell({
              shading: { fill: bg },
              children: [new Paragraph({ children: [new TextRun({ text: r.CaseNo, bold: true })] })],
            }),
            new TableCell({
              shading: { fill: bg },
              children: [new Paragraph(formatToDisplayDate(r.JudgementDate) || '—')],
            }),
            new TableCell({
              shading: { fill: bg },
              children: [new Paragraph(formatToDisplayDate(r.DraftDate) || '—')],
            }),
            new TableCell({
              shading: { fill: bg },
              children: [new Paragraph(formatToDisplayDate(r.FinalDate) || '—')],
            }),
            new TableCell({
              shading: { fill: bg },
              children: [new Paragraph(formatToDisplayDate(r.SendToSectionDate) || '—')],
            }),
            new TableCell({
              shading: { fill: bg },
              children: [new Paragraph(r.Remarks || '')],
            }),
          ],
        });
      }),
    ];

    const doc = new Document({
      sections: [
        {
          headers: {
            default: new Header({
              children: [
                new Paragraph({
                  alignment: AlignmentType.RIGHT,
                  children: [new TextRun({ text: 'VOLUMNBOOK — Official Office Records', color: '94A3B8', size: 18 })],
                }),
              ],
            }),
          },
          footers: {
            default: new Footer({
              children: [
                new Paragraph({
                  alignment: AlignmentType.RIGHT,
                  children: [
                    new TextRun({ text: 'Generated by VolumnBook  |  Page ' }),
                    new TextRun({ children: [PageNumber.CURRENT] }),
                    new TextRun({ text: ' of ' }),
                    new TextRun({ children: [PageNumber.TOTAL_PAGES] }),
                  ],
                }),
              ],
            }),
          },
          children: [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'VOLUMNBOOK',
                  bold: true,
                  size: 32,
                  color: '1E3A8A',
                }),
              ],
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Case & Judgement Volume Management System',
                  color: '64748B',
                  size: 22,
                }),
              ],
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: `Report: ${title}`,
                  bold: true,
                  size: 24,
                }),
              ],
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: `Generated: ${generatedAt}  |  ${filterInfo}  |  Total Records: ${records.length}`,
                  color: '64748B',
                  size: 18,
                }),
              ],
            }),
            new Paragraph({ text: '' }),
            new Table({
              width: { size: 100, type: WidthType.PERCENTAGE },
              rows: tableRows,
            }),
          ],
        },
      ],
    });

    const blob = await Packer.toBlob(doc);
    const filename = `VolumnBook_Report_${getTodayDbDate()}.docx`;
    triggerFileDownload(blob, filename);
    logger.info('EXPORT', `Word document (.docx) exported successfully: ${filename} (${records.length} records)`);
  } catch (err: any) {
    logger.error('EXPORT', `Failed to export DOCX: ${err?.message}`);
    throw err;
  }
}

/**
 * Export records as Excel spreadsheet (.xls or .xlsx)
 */
export async function exportToExcel(records: VolumeRecord[], format: 'xls' | 'xlsx' = 'xls', options: ExportReportOptions = {}): Promise<void> {
  try {
    const sheetData = [
      // Meta row
      ['VOLUMNBOOK — Case & Judgement Volume Management System'],
      [`Report: ${options.title || 'All Records'}`],
      [`Generated: ${formatFullDateTime(new Date())}`],
      [`Total Records: ${records.length}`],
      [], // blank line
      // Table Header
      ['Serial No', 'Case No', 'Judgement Date', 'Draft Date', 'Final Date', 'Send To Section Date', 'Remarks', 'Created At'],
      // Records
      ...records.map((r) => [
        r.SerialNo,
        r.CaseNo,
        formatToDisplayDate(r.JudgementDate) || '',
        formatToDisplayDate(r.DraftDate) || '',
        formatToDisplayDate(r.FinalDate) || '',
        formatToDisplayDate(r.SendToSectionDate) || '',
        r.Remarks || '',
        formatFullDateTime(new Date(r.CreatedAt)),
      ]),
    ];

    const worksheet = XLSX.utils.aoa_to_sheet(sheetData);

    // Set column widths
    worksheet['!cols'] = [
      { wch: 12 }, // Serial No
      { wch: 25 }, // Case No
      { wch: 16 }, // Judgement Date
      { wch: 16 }, // Draft Date
      { wch: 16 }, // Final Date
      { wch: 22 }, // Send To Section Date
      { wch: 40 }, // Remarks
      { wch: 22 }, // Created At
    ];

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'VolumeBook');

    const extension = format === 'xlsx' ? 'xlsx' : 'xls';
    const filename = `VolumnBook_Report_${getTodayDbDate()}.${extension}`;

    XLSX.writeFile(workbook, filename, { bookType: format === 'xlsx' ? 'xlsx' : 'biff8' });
    logger.info('EXPORT', `Excel file (.${extension}) exported successfully: ${filename} (${records.length} records)`);
  } catch (err: any) {
    logger.error('EXPORT', `Failed to export Excel: ${err?.message}`);
    throw err;
  }
}
